server:
  port: 8080
#  servlet:
#    context-path: /identity

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/demoversion2"
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
logging:
  level:
    org:
      springframework:
        security: debug
        web: debug

jwt:
  privateKey: WoOXNLcTzDlQqjp2JzMNJ7+fi7UQ3O8FAselbtKQSgM=

fileUpLoad:
  rootPath: D:\UML SWP\uploads