server:
  port: 8080

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/yachtdu"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
  h2:
    console:
      enabled: true

logging:
  level:
    org:
      springframework:
        security: debug
        web: debug

jwt:
  privateKey: WoOXNLcTzDlQqjp2JzMNJ7+fi7UQ3O8FAselbtKQSgM=

fileUpLoad:
  rootPath: D:\UML SWP\uploads

payment:
  vnPay:
    payUrl: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    tmnCode: OCFL0E29
    secretKey: IOMD65I4028IUX9GDIKR3NO583UOKRNW
    returnUrl: localhost:300
    apiUrl: https://sandbox.vnpayment.vn/merchant_webapi/api/transaction
    version: 2.1.0
    command: pay
    orderType: other
