server:
  port: 12759
spring:
  datasource:
    url: "jdbc:mysql://avnadmin:AVNS_1BYeDdH1Ewd3RXz1JJx@mysql-3f707c5a-dinhvuong2311-b1c2.i.aivencloud.com:12759/defaultdb?ssl-mode=REQUIRED"
    username: avnadmin
    password: AVNS_1BYeDdH1Ewd3RXz1JJx
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    open-in-view: false
  h2:
    console:
      enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: mailsender.bookingyacht@gmail.com
    password: dmab ocgy nypw hgbe
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
        transport:
          protocol: smtp

logging:
  level:
    org:
      springframework:
        security: debug
        web: debug

jwt:
  privateKey: WoOXNLcTzDlQqjp2JzMNJ7+fi7UQ3O8FAselbtKQSgM=

payment:
  vnPay:
    payUrl: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    tmnCode: OCFL0E29
    secretKey: IOMD65I4028IUX9GDIKR3NO583UOKRNW
    returnUrl: https://yb.sh.io.vn/payment-return
    apiUrl: https://sandbox.vnpayment.vn/merchant_webapi/api/transaction
    version: 2.1.0
    command: pay
    orderType: other


cloudinary:
  cloud_name: dxnr9gqy9
  api_key: 425361741734388
  api_secret: 134ZY5c7HUt3x9x2U0j9iiCKVWk
